<h1>Broadcasting</h1>

In [51]:
import numpy as np

In [52]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [53]:
# shape
my_3D_array.shape

(2, 7, 5)

In [54]:
# number of dimensions 
my_3D_array.ndim

3

In [55]:
# size; number of elements
my_3D_array.size

70

In [56]:
# data type for each element
my_3D_array.dtype

dtype('int64')

In [57]:
5 * my_3D_array - 2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [58]:
left_mat = np.arange(6).reshape((2, 3))
right_mat = np.arange(15).reshape((3, 5))

In [59]:
left_mat

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
right_mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
np.inner(left_mat, right_mat)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [62]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

### Operations along axes

In [63]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [64]:
my_3D_array.shape

(2, 7, 5)

In [65]:
my_3D_array.sum()

2415

In [66]:
(69 * 70)/2

2415

In [67]:
my_3D_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [68]:
my_3D_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [69]:
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

### Broadcasting Rules

In [70]:
my_2D_array = np.ones(35, dtype='int_').reshape((7, 5)) * 3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [71]:
my_random_2D_array = np.random.random((7, 5))
my_random_2D_array

array([[ 0.153 ,  0.2982,  0.2109,  0.6831,  0.2767],
       [ 0.6193,  0.1197,  0.2801,  0.5199,  0.9938],
       [ 0.7812,  0.0281,  0.9457,  0.5557,  0.9127],
       [ 0.9145,  0.2759,  0.2922,  0.8909,  0.9771],
       [ 0.7989,  0.5955,  0.3144,  0.743 ,  0.5335],
       [ 0.5269,  0.6966,  0.0921,  0.7488,  0.9242],
       [ 0.0222,  0.7834,  0.1705,  0.0288,  0.7261]])

In [72]:
np.set_printoptions(precision=4)
my_3D_array * my_random_2D_array

array([[[  0.    ,   0.2982,   0.4217,   2.0494,   1.1069],
        [  3.0963,   0.7185,   1.9606,   4.1589,   8.9446],
        [  7.8116,   0.3092,  11.3485,   7.2244,  12.7781],
        [ 13.7176,   4.415 ,   4.9672,  16.0361,  18.5646],
        [ 15.9782,  12.506 ,   6.9159,  17.0882,  12.8038],
        [ 13.1725,  18.1105,   2.4875,  20.9667,  26.8019],
        [  0.6661,  24.2861,   5.4566,   0.9516,  24.6872]],

       [[  5.3556,  10.7352,   7.8019,  25.9594,  10.7925],
        [ 24.77  ,   4.9095,  11.7635,  22.3543,  43.7292],
        [ 35.1522,   1.2928,  44.4484,  26.6746,  44.7232],
        [ 45.7254,  14.0727,  15.1938,  47.2174,  52.7626],
        [ 43.94  ,  33.3493,  17.9184,  43.092 ,  31.476 ],
        [ 31.6141,  42.4901,   5.7121,  47.175 ,  59.1491],
        [  1.4433,  51.7058,  11.4248,   1.9608,  50.1006]]])

In [76]:
my_vector = np.arange(5) * 7 
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [82]:
my_3D_array / my_vector.astype(np.float64)

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [78]:
result = my_3D_array % my_vector
result

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]])