### Attributes of NumPy Arrays
- Number of dimensions
- shape
- size (number of elements)
- data type for elements
- item size for each element within an array
- type (for the array; not for elements within array)

https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#array-attributes

In [77]:
import numpy as np

In [78]:
a = np.arange(24).reshape((2, 3, 4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [79]:
type(a)

numpy.ndarray

In [96]:
a.dtype

dtype('int64')

In [80]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [81]:
a.shape

(2, 3, 4)

In [82]:
a.strides

(96, 32, 8)

In [83]:
a.ndim

3

In [84]:
a.data

In [85]:
a.size

24

In [86]:
a.itemsize

8

In [87]:
a.nbytes

192

In [88]:
a.base

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [89]:
b = a.ctypes
b

In [90]:
hex(id(b))

'0x10d9965f8'

In [91]:
a.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [92]:
a.real

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [93]:
a.imag

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [94]:
a.flat

In [95]:
list(a.flat)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23]