<h1>Creating Structured Arrays</h1>

In [1]:
import numpy as np

In [3]:
person_data_def = [('name','S6'),('height','f8'),('weight','f8'), ('age', 'i8')]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [5]:
people_array = np.zeros((4), dtype=person_data_def)

In [6]:
people_array

array([('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0),
       ('', 0.0, 0.0, 0)], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [7]:
people_array[3] = ('Delta', 73, 205, 34)

In [8]:
people_array

array([('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0),
       ('Delta', 73.0, 205.0, 34)], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [9]:
people_array[0] = ('Alpha', 65, 112, 23)

In [10]:
people_array

array([('Alpha', 65.0, 112.0, 23), ('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0),
       ('Delta', 73.0, 205.0, 34)], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [11]:
people_array[0:]

array([('Alpha', 65.0, 112.0, 23), ('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0),
       ('Delta', 73.0, 205.0, 34)], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [12]:
ages = people_array['age']

In [13]:
ages

array([23,  0,  0, 34])

In [18]:
make_youthful = ages / 2.0

In [19]:
make_youthful

array([ 11.5,   0. ,   0. ,  17. ])

In [20]:
people_array

array([('Alpha', 65.0, 112.0, 23), ('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0),
       ('Delta', 73.0, 205.0, 34)], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

### Multi-dimensional Structured Arrays

In [21]:
people_big_array = np.zeros((4,3,2), dtype=person_data_def)
people_big_array

array([[[('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)]],

       [[('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)]],

       [[('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)]],

       [[('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)]]], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [23]:
people_big_array[3,2,1] = ('Echo', 68, 155, 46)

In [24]:
people_big_array

array([[[('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)]],

       [[('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)]],

       [[('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)]],

       [[('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('', 0.0, 0.0, 0)],
        [('', 0.0, 0.0, 0), ('Echo', 68.0, 155.0, 46)]]], 
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [25]:
people_big_array['height']

array([[[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,   0.]],

       [[  0.,   0.],
        [  0.,   0.],
        [  0.,  68.]]])

In [26]:
people_big_array[['height', 'weight']]

array([[[(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)]],

       [[(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)]],

       [[(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)]],

       [[(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (0.0, 0.0)],
        [(0.0, 0.0), (68.0, 155.0)]]], 
      dtype=[('height', '<f8'), ('weight', '<f8')])

### Creating Record Array

In [27]:
person_record_array = np.rec.array([('Delta', 73, 205, 34), ('Alpha', 65, 112, 23)], dtype=person_data_def)
person_record_array

rec.array([('Delta', 73.0, 205.0, 34), ('Alpha', 65.0, 112.0, 23)], 
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [28]:
person_record_array[0]

('Delta', 73.0, 205.0, 34)

In [29]:
person_record_array[0].age

34