In [28]:
import numpy as np

In [29]:
mi_casa = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [30]:
su_casa = mi_casa

### Same or Different

In [31]:
# Reference equality
mi_casa is su_casa

True

In [32]:
id(mi_casa)

4394607600

In [33]:
id(su_casa)

4394607600

In [34]:
# Value equality
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [35]:
su_casa[4]

2

In [36]:
su_casa[4] = 1010

In [37]:
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [38]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [39]:
mi_casa[2]

-12

In [40]:
mi_casa[2] = -22

In [41]:
mi_casa

array([ -45,  -31,  -22,    0, 1010,   25,   51,   99])

In [42]:
su_casa

array([ -45,  -31,  -22,    0, 1010,   25,   51,   99])

In [43]:
id(mi_casa)

4394607600

In [44]:
id(su_casa)

4394607600

In [45]:
tree_house = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [46]:
tree_house == mi_casa

array([ True,  True, False,  True, False,  True,  True,  True], dtype=bool)

In [47]:
id(tree_house)

4394639728

In [48]:
hex(id(tree_house))

'0x105f0e170'

In [55]:
id(mi_casa)

4394607600

In [56]:
tree_house[0] = 214

In [57]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [58]:
mi_casa

array([ -45,  -31,  -22,    0, 1010,   25,   51,   99])

In [59]:
tree_house == mi_casa

array([False,  True, False,  True, False,  True,  True,  True], dtype=bool)

In [61]:
tree_house is mi_casa

False

### View: A shallow copy
Information about views is available at https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.view.html

In [62]:
farm_house = tree_house.view()

In [63]:
farm_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [64]:
hex(id(tree_house))

'0x105f0e170'

In [65]:
hex(id(farm_house))

'0x105f14580'

In [66]:
farm_house.shape = (2, 4)

In [67]:
farm_house

array([[214, -31, -12,   0],
       [  2,  25,  51,  99]])

In [68]:
hex(id(farm_house))

'0x105f14580'

In [69]:
tree_house[3] = -111

In [70]:
farm_house

array([[ 214,  -31,  -12, -111],
       [   2,   25,   51,   99]])

In [71]:
tree_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])

In [72]:
hex(id(tree_house))

'0x105f0e170'

In [73]:
hex(id(farm_house))

'0x105f14580'

### Deep Copy

In [74]:
dog_house = np.copy(tree_house)
dog_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])

In [75]:
id(dog_house)

4394673136

In [76]:
id(tree_house)

4394639728

In [78]:
dog_house[0] = -121
dog_house

array([-121,  -31,  -12, -111,    2,   25,   51,   99])

In [79]:
tree_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])