# Brain Teasers
for more brain teasers, please see: http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

In [1]:
import numpy as np

np.set_printoptions(precision=2)

## What version of NumPy are you using?

In [2]:
# note double underscrore 
print(np.__version__)

1.11.2


### Display array elements in reverse order

In [3]:
my_array = np.array(np.arange(10))
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Triple elements in array

In [5]:
my_array * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

### Create array with 20 zeros; every fifth element equals four

In [6]:
my_array = np.zeros(20)
my_array[0::5] = 4
my_array

array([ 4.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  4.,  0.,  0.,
        0.,  0.,  4.,  0.,  0.,  0.,  0.])

### Create a 3x3 matrix whose elements equal 0 through 8

In [7]:
my_matrix = np.asmatrix(np.array(np.arange(9)).reshape((3,3)))
my_matrix

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

### Transpose the rows and columns

In [8]:
my_matrix.T

matrix([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

### Create a 5x5 identity matrix with integer components

In [9]:
my_matrix = np.asmatrix(np.eye(5, dtype='int'))
my_matrix

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

### Find the mean of a vector with 30 random elements.  Can you guess the approximate value for the mean?

In [10]:
my_random_vector = np.random.random(30)
my_random_vector.mean()

0.58031087435606332

### Repeat, and visually estimate the mean for the sum of the two means

In [11]:
my_random_vector = np.random.random(30)
my_random_vector.mean()

0.49361299890880844

### Create a 2d array with ones on the border and zeros inside the border

In [12]:
my_bordered_array = np.ones((5,5))
my_bordered_array[1:-1,1:-1] = 0
my_bordered_array

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

### Create an 8x8 checker board with alternating zeros and ones

In [13]:
my_checker_board = np.zeros((8,8),dtype=int)
my_checker_board[1::2,::2] = 1
my_checker_board[::2,1::2] = 1
print(my_checker_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [14]:
my_alternative_checker_board = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(my_alternative_checker_board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Create a sorted vector that contain 'n' random numbers

In [15]:
vector_size = 12
my_random_vector = np.random.random(vector_size)
my_sorted_random_vector = np.sort(my_random_vector)
print (my_sorted_random_vector)

[ 0.08  0.08  0.12  0.16  0.27  0.27  0.5   0.54  0.55  0.84  0.88  0.94]


### Without sorting, replace largest element in random array with the value 1234

In [16]:
my_random_vector[my_random_vector.argmax()] = 1234
my_random_vector

array([  1.16e-01,   8.42e-01,   5.52e-01,   7.88e-02,   1.57e-01,
         2.68e-01,   5.40e-01,   1.23e+03,   7.85e-02,   8.82e-01,
         4.97e-01,   2.74e-01])

### Given the following data type and data set; sort according to 'height'

source: http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html

In [17]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]

In [18]:
camelot_structured_array = np.array(camelot_values, dtype=camelot_dtype)
camelot_sorted_array = np.sort(camelot_structured_array, order='height')
for n in np.arange(camelot_sorted_array.size):
    print (camelot_sorted_array[n])

('Galahad', 1.7, 38)
('Arthur', 1.8, 41)
('Lancelot', 1.9, 38)


### Make an array read-only (immutable)

In [19]:
my_ordinary_array = np.array(np.arange(12))
my_ordinary_array.flags.writeable = False
my_ordinary_array[5] = 1234

ValueError: assignment destination is read-only

### Print enumerated values from a 3x3 NumPy array

In [ ]:
my_3_3_array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(my_3_3_array):
    print(index, value)
